"""
Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle
 
T_n=n(n+1)/2
 
1, 3, 6, 10, 15, ...
Pentagonal
 
P_n=n(3n - 1)/2
 
1, 5, 12, 22, 35, ...
Hexagonal
 
H_n=n(2n - 1)
 
1, 6, 15, 28, 45, ...
It can be verified that T_{285} = P_{165} = H_{143} = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

Link to the problem:
    https://projecteuler.net/problem=45
"""

def triangular_pentagonal_hexagonal(limit: int) -> int:
    result = []
    pentagonal = set()
    hexagonal = set()

    for n in range(1, limit+1):
        # triangular.add(n*(n+1))
        pentagonal.add(int(n*(3*n-1)/2))
        hexagonal.add(int(n*(2*n-1)))
    
    for t in range(2, limit+1):
        tri = int(t*(t+1)/2)

        if tri in pentagonal and tri in hexagonal:
            result.append(tri)
    return result
    
if __name__ == "__main__": 
    answer = triangular_pentagonal_hexagonal(100000)
    print(f"The answer is {answer[-1]}")